#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

CONFIG="/config/services/docker"

case "$1" in
    remove)
        ;;

    purge)
        if omv_config_exists $CONFIG; then
            echo "Deleting Configuration"
            omv_config_delete $CONFIG;
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
